[project]
name = "mocvxpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "cvxpy>=1.6.5",
    "dask>=2025.5.1",
    "gurobipy>=12.0.1",
    "matplotlib>=3.10.1",
    "mosek>=11.0.18",
    "numpy>=2.3.0",
    "ppprint>=0.1.0",
    "pycddlib>=3.0.2",
]
